# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_emtion.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Emotions(object):
    def setupUi(self, Emotions):
        Emotions.setObjectName("Emotions")
        Emotions.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Emotions)
        self.centralwidget.setObjectName("centralwidget")
        self.pic = QtWidgets.QGraphicsView(self.centralwidget)
        self.pic.setGeometry(QtCore.QRect(20, 20, 531, 501))
        self.pic.setObjectName("pic")
        self.text = QtWidgets.QTextBrowser(self.centralwidget)
        self.text.setGeometry(QtCore.QRect(560, 20, 221, 311))
        self.text.setObjectName("text")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(560, 340, 221, 181))
        self.textEdit.setObjectName("textEdit")
        Emotions.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Emotions)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.data = QtWidgets.QMenu(self.menubar)
        self.data.setObjectName("data")
        self.kmeans = QtWidgets.QMenu(self.menubar)
        self.kmeans.setObjectName("kmeans")
        self.knn = QtWidgets.QMenu(self.menubar)
        self.knn.setObjectName("knn")
        self.about = QtWidgets.QMenu(self.menubar)
        self.about.setObjectName("about")
        Emotions.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Emotions)
        self.statusbar.setObjectName("statusbar")
        Emotions.setStatusBar(self.statusbar)
        self.cutA = QtWidgets.QAction(Emotions)
        self.cutA.setCheckable(False)
        self.cutA.setChecked(False)
        self.cutA.setObjectName("cutA")
        self.cutB = QtWidgets.QAction(Emotions)
        self.cutB.setObjectName("cutB")
        self.interface1 = QtWidgets.QAction(Emotions)
        self.interface1.setObjectName("interface1")
        self.index1 = QtWidgets.QAction(Emotions)
        self.index1.setCheckable(True)
        self.index1.setChecked(False)
        self.index1.setObjectName("index1")
        self.interface2 = QtWidgets.QAction(Emotions)
        self.interface2.setObjectName("interface2")
        self.index2 = QtWidgets.QAction(Emotions)
        self.index2.setObjectName("index2")
        self.load_data = QtWidgets.QAction(Emotions)
        self.load_data.setObjectName("load_data")
        self.id = QtWidgets.QAction(Emotions)
        self.id.setObjectName("id")
        self.time = QtWidgets.QAction(Emotions)
        self.time.setObjectName("time")
        self.start1 = QtWidgets.QAction(Emotions)
        self.start1.setObjectName("start1")
        self.start2 = QtWidgets.QAction(Emotions)
        self.start2.setObjectName("start2")
        self.data.addAction(self.cutA)
        self.data.addAction(self.cutB)
        self.kmeans.addAction(self.interface1)
        self.kmeans.addAction(self.index1)
        self.kmeans.addAction(self.start1)
        self.knn.addAction(self.interface2)
        self.knn.addAction(self.index2)
        self.knn.addAction(self.start2)
        self.about.addAction(self.id)
        self.menubar.addAction(self.data.menuAction())
        self.menubar.addAction(self.kmeans.menuAction())
        self.menubar.addAction(self.knn.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(Emotions)
        QtCore.QMetaObject.connectSlotsByName(Emotions)

    def retranslateUi(self, Emotions):
        _translate = QtCore.QCoreApplication.translate
        Emotions.setWindowTitle(_translate("Emotions", "Emotions"))
        self.textEdit.setHtml(_translate("Emotions", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; background-color:#ffffff;\"><span style=\" font-family:\'JetBrains Mono\',\'monospace\'; font-size:12pt; font-weight:600; color:#aaaaff;\">0: &quot;Angry&quot;,<br />1: &quot;Disgust&quot;,<br />2: &quot;Fear&quot;,<br />3: &quot;Happy&quot;,<br />4: &quot;Sad&quot;,<br />5: &quot;Surprise&quot;,<br />6: &quot;Neutral&quot;</span></p></body></html>"))
        self.data.setTitle(_translate("Emotions", "数据准备"))
        self.kmeans.setTitle(_translate("Emotions", "K均值"))
        self.knn.setTitle(_translate("Emotions", "K近邻"))
        self.about.setTitle(_translate("Emotions", "关于"))
        self.cutA.setText(_translate("Emotions", "原始数据"))
        self.cutB.setText(_translate("Emotions", "人脸对齐后"))
        self.interface1.setText(_translate("Emotions", "聚类对比"))
        self.index1.setText(_translate("Emotions", "查看单个聚类效果"))
        self.interface2.setText(_translate("Emotions", "分类对比"))
        self.index2.setText(_translate("Emotions", "查看单个分类效果"))
        self.id.setText(_translate("Emotions", "系统信息"))
        self.start1.setText(_translate("Emotions", "开始聚类"))
        self.start2.setText(_translate("Emotions", "开始分类"))
